dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
  - "3.8-dev"  # 3.8 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script:
  - py.test -v -q --flakes --cov-config=.coveragerc --cov=hubstaff --cov-report=term-missing --doctest-modules tests
after_success:
  - coveralls
